
services:
  backend:
    container_name: backend
    build: ./Python/
    ports:
      - "8000:8000"
    networks:
      - network
    volumes:
      - data:/usr/src/app/ArtificialQI

  frontend:
    container_name: frontend
    build: ./NodeJS/
    ports:
      - "3000:3000"
    networks:
      - network
    volumes:
      - data:/usr/src/app/ArtificialQI
    depends_on:
      - backend

  ollama:
    container_name: ollama
    tty: true
    restart: always
    build: ./Ollama/
    ports:
      - "5000:5000"
    networks:
      - network
    depends_on:
      - frontend
      - backend

volumes:
  data:

networks:
  network:
    driver: bridge



