
services:
  backend:
    container_name: backend
    build: ./Python/
    ports:
      - "8000:8000"
    networks:
      - network
    volumes:
      - data:/usr/src/app/ArtificialQI

  frontend:
    container_name: frontend
    build: ./NodeJS/
    ports:
      - "3000:3000"
    networks:
      - network
    volumes:
      - data:/usr/src/app/ArtificialQI
    depends_on:
      - backend

volumes:
  data:

networks:
  network:
    driver: bridge



